- activation of hotplug-based mounting and unmounting of storages in the helper scripts

diff --git a/debian/data/nubisave-unmounter b/debian/data/nubisave-unmounter
--- a/debian/data/nubisave-unmounter
+++ b/debian/data/nubisave-unmounter
@@ -3,17 +3,17 @@
 # Unmounts all configured Nubisave directories
 # Useful for headless configurations
 
-storagedir=~/.nubisave/storages
+storagesdir=~/.nubisave/storages
 configdir=~/.nubisave/db/splitter_configuration
 splitterdir=/usr/share/nubisave/splitter/
 
-if [ ! -d $configdir ] || [ ! -d $storagedir ]
+if [ ! -d $configdir ] || [ ! -d $storagesdir ]
 then
-	echo "Error: Configuration directory $configdir and/or storage directory $storagedir does not exist." >&2
+	echo "Error: Configuration directory $configdir and/or storage directory $storagesdir does not exist." >&2
 	exit 1
 fi
 
-cd $storagedir
+cd $storagesdir
 if [ -z "`ls`" ]
 then
 	echo "No storage modules configured and mounted, not unmounting anything."
@@ -35,11 +35,16 @@ do
 			unmount=`echo $mount | sed -e "s& $param& $paramval&"`
 		fi
 	done
-	mountpoint=$storagedir/$storage
+
+	mountpoint=$storagesdir/$storage
 	unmount=`echo $unmount | sed -e "s& mountpoint& $mountpoint&"`
 	echo "* unmount: $unmount"
 
-	cd $splitterdir
-	$unmount
-	cd $configdir
+	# Hot-plugging for indirect unmounting through Nubisave
+	rm $storage
+
+	# Deprecated: Manual unmounting
+	#cd $splitterdir
+	#$unmount
+	#cd $configdir
 done
